### PR TITLE
fix #935 fix the problem of application clock

### LINKED ISSUE #935: [UI] the application clock may forward crazily
Tring to figure out how to reproduce it

### PR DESCRIPTION
**Pull request by skw1992**

### CODE REVIEW

File: services/dashboard/views/apps/app/appdag.js [hunk 1]
```diff
@@ -14,19 +14,23 @@ angular.module('dashboard.apps.appmaster')
...
       if (nowLocal - previousDetectPoint.local > detectPeriod * 1000) {
-        $interval.cancel(updateClockPromise);
-        if (nowAppClock - previousDetectPoint.appClock > 0) {
-          var clockDelta = nowAppClock - $scope.displayClock;
-          appClockRate = 1000 * (nowLocal - previousDetectPoint.local) /
-            (nowAppClock  - previousDetectPoint.appClock + clockDelta);
-          updateClockPromise = $interval(function () {
-            $scope.displayClock += 1000;
-          }, appClockRate);
+        if (appClockInited) {
```
Comment (clockfly) [inline services/dashboard/views/apps/app/appdag.js]: If appClockInited = false, previousDetectPoint should be initiated immediately instead of waiting for 15 seconds.

Comment (clockfly) [inline services/dashboard/views/apps/app/appdag.js]: Everytime ('app.clock', function(nowAppClock) is changed, the display clock should be updated.

Comment (clockfly) [inline services/dashboard/views/apps/app/appdag.js]: during the interval of two change of app.clock, the display clock should use the simulated clock.

**Comment by huafengw** [comment]
+1
