### PR TITLE
fix #1192 Potential message loss exception in ExpressTransport

### LINKED ISSUE #1192: Potential message lost exception in ExpressTransport
The remoteAddressMap in Express should not include localhost

### PR DESCRIPTION
**Pull request by huafengw**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/1193)

### CODE REVIEW

File: streaming/src/main/scala/org/apache/gearpump/streaming/executor/Executor.scala [hunk 1]
```diff
@@ -116,8 +116,9 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
         taskIdList.map(taskId => (TaskId.toLong(taskId), host))
       }
       express.startClients(locations.keySet).map { _ =>
```
Comment (clockfly) [inline streaming/src/main/scala/org/apache/gearpump/streaming/executor/Executor.scala]: startClients will still connect to local host?

Comment (huafengw) [inline streaming/src/main/scala/org/apache/gearpump/streaming/executor/Executor.scala]: Nope, the startClients will also exclude the localhost.

**Comment by clockfly** [comment]
+1
