### PR TITLE
fix #474, fix rest service UT fail.

### LINKED ISSUE #474: rest service UT fails
Check https://travis-ci.org/intel-hadoop/gearpump/builds/50595725

Seems the we don't handle the rest server start/stop in good way.

### PR DESCRIPTION
**Pull request by clockfly**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/475)

### CODE REVIEW

File: services/src/main/scala/org/apache/gearpump/services/AppMasterService.scala [hunk 1]
```diff
@@ -34,7 +34,7 @@ import scala.util.{Failure, Success, Try}
 
 trait AppMasterService extends HttpService  {
   import upickle._
-  val master:ActorRef
+  def master:ActorRef
```
Comment (manuzhang) [inline services/src/main/scala/org/apache/gearpump/services/AppMasterService.scala]: what's wrong with the previous way ?

**Comment by stanleyxu2005** [comment]
+1

File: services/src/main/scala/org/apache/gearpump/services/AppMasterService.scala (hunk 1 above)
Comment (clockfly) [inline services/src/main/scala/org/apache/gearpump/services/AppMasterService.scala]: @manuzhang 

There is a contention.

Worker still have not register itself to master(because it start in async way) when the error happen.
