### PR TITLE
fix #301, fix UserConfig ClassNotFoundException by storing everything in...

### LINKED ISSUE #301: UserConfig may cause ClassNotfound
We allow user to store customized data in UserConfig,
which may cause ClassNotfoundException when the UserConfig is sent to master

### PR DESCRIPTION
**Pull request by clockfly**
... Config as String

[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/305)

### CODE REVIEW

File: examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala [hunk 1]
```diff
@@ -59,6 +62,9 @@ object KafkaWordCount extends App with ArgumentsParser {
 
   val config = parse(args)
   val context = ClientContext(config.getString("master"))
+
+  implicit val system = context.system
```
Comment (manuzhang) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: why add an implicit val here ?

File: streaming/src/main/scala/org/apache/gearpump/streaming/task/TaskContext.scala [hunk 2]
```diff
@@ -22,4 +22,4 @@ import akka.actor.ActorRef
 import org.apache.gearpump.streaming.DAG
 
 case class TaskContext(taskId : TaskId, executorId : Int, appId : Int,
-                      appMaster : ActorRef, dag : DAG)
\ No newline at end of file
+                      appMaster : ActorRef, parallism: Int, dag : DAG)
```
Comment (manuzhang) [inline streaming/src/main/scala/org/apache/gearpump/streaming/task/TaskContext.scala]: "parallelism" :)

File: examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala (hunk 1 above)
Comment (clockfly) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: ActorRef serialization requires an implicit actor system.

File: streaming/src/main/scala/org/apache/gearpump/streaming/task/TaskContext.scala (hunk 2 above)
Comment (clockfly) [inline streaming/src/main/scala/org/apache/gearpump/streaming/task/TaskContext.scala]: thanks, fixed

File: examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala (hunk 1 above)
Comment (manuzhang) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: which ActorRef ? Why SOL don't need this ?

Comment (clockfly) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: SOL doesn't have call to 
UserConfig.withValue(KafkaConfig.NAME, kafkaConfig)

Comment (clockfly) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: There are comment about akka serialization in definition of withValue and getValue:
https://github.com/clockfly/gearpump/blob/refactor_user_config/core/src/main/scala/org/apache/gearpump/cluster/UserConfig.scala

Comment (clockfly) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: I have refined the comments in UserConfig, which now explain why we need an implicit ActorSystem in scope.

Comment (clockfly) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: Further improve this,

add doc link to akka
```
+  /**
+   * This will de-serialize value to object instance
+   *
+   * To do de-serialization, this requires an implicit ActorSystem, as
+   * the ActorRef and possibly other akka classes deserialization
+   * requires an implicit ActorSystem.
+   *
+   * @see [[http://doc.akka.io/docs/akka/snapshot/scala/serialization.html#A_Word_About_Java_Serialization]]
+   */
```

Comment (manuzhang) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: ok, I see. Is there a way to hide this ? Like for the KafkaStreamProcessor, how about inheriting it from TaskActor ?

Comment (clockfly) [inline examples/kafka/src/main/scala/org/apache/gearpump/streaming/examples/kafka/wordcount/KafkaWordCount.scala]: Good point!

I have fixed this.

**Comment by manuzhang** [comment]
+1
