### PR TITLE
fix #1289, construct HTable at cluster side

### LINKED ISSUE #1289: HBaseSink can not work cause the HTable is not serializable

### PR DESCRIPTION
**Pull request by huafengw**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/1294)

### CODE REVIEW

**Comment by huafengw** [comment]
@kkasravi Hi Kam, I modified the HBaseSink, to align with the hbase-1.0 api, I found it difficult to allow DI for HTable, such as passing a function which return a HTable. Any advice on this pr?

File: external/hbase/src/test/scala/org/apache/gearpump/external/hbase/HBaseSinkSpec.scala [hunk 1]
```diff
@@ -38,6 +39,7 @@ class HBaseSinkSpec extends PropSpec with PropertyChecks with Matchers {
     val hbaseSink = HBaseSink(htable)
     hbaseSink.insert(put)
     verify(htable).put(put)
+    */
```
Comment (kkasravi) [inline external/hbase/src/test/scala/org/apache/gearpump/external/hbase/HBaseSinkSpec.scala]: Hi @huafengw 
Did this fail to serialize/deserialize?

Comment (huafengw) [inline external/hbase/src/test/scala/org/apache/gearpump/external/hbase/HBaseSinkSpec.scala]: When you construct a DataSinkProcessor, it will serialize the datasink to the UserConfig, which will fail if contains a HTable.

**Comment by clockfly** [comment]
If user want to write a DataSource, then he must make sure this DataSource is serializable with default java serializer?
This is too restrictive!

IMHO, there is nothing wrong about Kam's work on dependency injection for HBaseSInk, there is something wrong with how we define the DataSInk/DataSource usage model.

**Comment by kkasravi** [comment]
There was similar problem with KafkaSource as well I believe.

**Comment by huafengw** [comment]
I think make DataSink Serializable is inevitable, suppose user want to pass a hadoop configuration to the DataSink and the sink is not serializable, then he will has to be responsible for the configuration serialization.

**Comment by kkasravi** [comment]
@huafengw @clockfly 
For mocks, the pattern sometimes is to pass the mock via UserConfig, but this automatically means serialization/deserialization and Mockito mocks use dynamic proxies. Maybe there is a better way to do this.

**Comment by manuzhang** [comment]
I think the problem is the client-side source and server-side source is currently mixed in on class. The client-side source is used for configuration and DAG setups, which should be serializable since they are passed across the network to server. The server-side source does the real work at run time and there is no need for its member (e.g. HTable, KafkaProducer) to be serializable as they are created on server. Let me try to split the two.

**Comment by kkasravi** [comment]
+1
Perhaps this can also be applied with sink/source connectors in general.

**Comment by clockfly** [comment]
@manuzhang 

I am going to merge this one, as it is a bug fix. Please open new PR to propose the solution you mentioned.

**Comment by clockfly** [comment]
+1
