### PR TITLE
fix #562 fix AppMaster and Executor restart infinitely

### LINKED ISSUE #562: Gearpump will restart failed executors infinitely
When executor crash or appmaster crash, then it will trigger recovery process.
The current problem is that, if the error persist(for example, user code contains exception that is thrown everytime), then we will always trigger recovery, which may generate too much log files on disks.

The solution is to set a retry limit for the recovery. If we cannot recovery the app/executor/task after xx max tries, then we should stop and report this error to user.

### PR DESCRIPTION
**Pull request by huafengw**
[Review on Reviewable](https://reviewable.io/reviews/intel-hadoop/gearpump/574)

### CODE REVIEW

File: core/src/main/scala/org/apache/gearpump/util/RestartPolicy.scala [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+/**
+ * @param maxNrOfRetries the number of times is allowed to be restarted, negative value means no limit,
+ *   if the limit is exceeded the policy will not allow to restart
+ * @param withinTimeRange duration of the time window for maxNrOfRetries, Duration.Inf means no window
+ */
+class RestartPolicy (maxNrOfRetries: Int, withinTimeRange: Duration) {
+  private val status = new ChildRestartStats(null, 0, 0L)
+  private val retriesWindow = (Some(maxNrOfRetries), Some(withinTimeRange.toMillis.toInt))
+
+  def allowRestart: Boolean = {
```
Comment (clockfly) [inline core/src/main/scala/org/apache/gearpump/util/RestartPolicy.scala]: maybe change this to requestRestart?

File: streaming/src/main/scala/org/apache/gearpump/streaming/executor/ExecutorRestartPolicy.scala [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  def addTaskToExecutor(executorId: Int, taskId: TaskId): Unit = {
+    var taskSetForExecutorId = executorToTaskIds.getOrElse(executorId, Set.empty[TaskId])
+    taskSetForExecutorId += taskId
+    executorToTaskIds += executorId -> taskSetForExecutorId
+    if (!taskRestartPolocies.contains(taskId)) {
+      taskRestartPolocies += taskId -> new RestartPolicy(maxNrOfRetries, withinTimeRange)
+    }
+  }
+
+  def allowRestartExecutor(executorId: Int): Boolean = {
```
Comment (clockfly) [inline streaming/src/main/scala/org/apache/gearpump/streaming/executor/ExecutorRestartPolicy.scala]: maybe change to requestPermissionToRestartExecutor

**Comment by clockfly** [comment]
+1
